export const data = [
    {
        id: 1, name: 'Ant-Man', cost: 200, club: 'Action/Adventure', img: '../assets/images/film1.jpg',
        info: "During her days of entrapment in the Quantum Realm, Janet van Dyne encounters an exiled traveler named Kang. In the present day, after the Avengers' battle against Thanos, Scott Lang has become a successful memoirist and has been living happily with his girlfriend, Hope van Dyne. Scott's now-teenage daughter Cassie has become a political activist helping people displaced by the Blip, resulting in her having a strained relationship with her father. While visiting Hope's parents, Hank Pym and Janet, Cassie reveals that she has been working on a device that can establish contact with the Quantum Realm. Upon learning of this, Janet panics and forcefully shuts off the device, but the message is received, resulting in a portal that opens and sucks the five of them into the Quantum Realm. Scott and Cassie are found by natives who are rebelling against their ruler, while Hope, Janet, and Pym explore a sprawling city to get answers.",
        clip: 'https://www.youtube.com/embed/ZlNFpri-Y40',
        qc: '../assets/images/qc1.jpg',
        dt: ['../assets/images/dt1a.jpg', '../assets/images/dt1b.jpg', '../assets/images/dt1c.jpg', '../assets/images/dt1d.jpg'],
    },
    {
        id: 2, name: 'Avatar', cost: 230, club: 'Psychology/Science/Fiction', img: '../assets/images/film2.jpg',
        info: "Avatar: The Way of Water is a 2022 American epic science fiction film directed and produced by James Cameron. He co-wrote the screenplay with Rick Jaffa and Amanda Silver from a story the trio wrote with Josh Friedman and Shane Salerno. Distributed by 20th Century Studios, it is the sequel to Avatar (2009) and the second installment in the Avatar film series. Cast members Sam Worthington, Zoe Saldaña, Stephen Lang, Joel David Moore, CCH Pounder, Giovanni Ribisi, Dileep Rao, and Matt Gerald reprise their roles from the original film, with Sigourney Weaver returning in an additional role[6] while Kate Winslet joined the cast. It follows a blue-skinned humanoid Na'vi named Jake Sully (Worthington) as he and his family, under renewed human threat, seek refuge with the aquatic Metkayina clan of Pandora, a habitable exomoon on which they live.",
        clip: 'https://www.youtube.com/embed/d9MyW72ELq0',
        qc: '../assets/images/qc2.jpg',
        dt: ['../assets/images/dt2a.jpg', '../assets/images/dt2b.jpg', '../assets/images/dt2c.jpg', '../assets/images/dt2d.jpg'],
    },
    {
        id: 3, name: 'Sisu', cost: 500, club: 'Action/Historical', img: '../assets/images/film3.jpg',
        info: 'After Finland loses the Continuation War in late 1944, the Soviet Union agrees to end hostilities if all German soldiers are expelled from Finland. This causes the German forces to retaliate against the Finns, leading to the Lapland War. Retired commando and prospector Aatami Korpi lives alone with only his horse and his faithful dog in the remote wilderness of Lapland. Aatami spends his days panning and mining in search of gold. He sees battles taking place in the distance, but takes little interest in them. After uncovering a rich gold deposit, he collects a hefty amount of nuggets and mounts his horse, heading for the nearest town with his dog in tow.',
        clip: 'https://www.youtube.com/embed/d2k4QAItiSA',
        qc: '../assets/images/qc3.jpg',
        dt: ['../assets/images/dt3a.jpg', '../assets/images/dt3b.jpg', '../assets/images/dt3c.jpg', '../assets/images/dt3d.jpg'],
    },
    {
        id: 4, name: 'Fast X', cost: 220, club: 'Action/Adventure', img: '../assets/images/film4.jpg',
        info: "Over many missions and against impossible odds, Dom Toretto and his family have outsmarted and outdriven every foe in their path. Now, they must confront the most lethal opponent they've ever faced. Fueled by revenge, a terrifying threat emerges from the shadows of the past to shatter Dom's world and destroy everything -- and everyone -- he loves.",
        clip: 'https://www.youtube.com/embed/32RAq6JzY-w',
        qc: '../assets/images/qc4.jpg',
        dt: ['../assets/images/dt4a.jpg', '../assets/images/dt4b.jpg', '../assets/images/dt4c.jpg', '../assets/images/dt4d.jpg'],
    },
    {
        id: 5, name: 'Simulant', cost: 900, club: 'Fantasy', img: '../assets/images/film5.jpg',
        info: "A humanoid A.I.'s attempt at winning a grieving widow's heart puts it in the path of a government agent trying to stop the rise of machine consciousness.",
        clip: 'https://www.youtube.com/embed/EybgsZtCDF8',
        qc: '../assets/images/qc5.jpg',
        dt: ['../assets/images/dt5a.jpg', '../assets/images/dt5b.jpg', '../assets/images/dt5c.jpg', '../assets/images/dt5d.jpg'],
    },
    {
        id: 6, name: 'King Kong', cost: 150, club: 'Adventure/Fantasy', img: '../assets/images/film6.jpg',
        info: 'When a film crew visits a mysterious island for a shoot, they discover a giant prehistoric ape living there. Mayhem ensues when the gorilla attempts to possess a woman from the crew.',
        clip: 'https://www.youtube.com/embed/PbrikL8IjXM',
        qc: '../assets/images/qc6.jpg',
        dt: ['../assets/images/dt6a.jpg', '../assets/images/dt6b.jpg', '../assets/images/dt6c.jpg', '../assets/images/dt6d.jpg'],
    },
    {
        id: 7, name: 'The Lake', cost: 400, club: 'Action/Fiction', img: '../assets/images/film7.jpg',
        info: 'A girl finds a strange egg and brings it back to her village, only to later realize it was from a monster. Now a giant monster emerges from the lake to search for the egg, destroying the town and its inhabitants.',
        clip: 'https://www.youtube.com/embed/XpiKECv9Xbk',
        qc: '../assets/images/qc7.jpg',
        dt: ['../assets/images/dt7a.jpg', '../assets/images/dt7b.jpg', '../assets/images/dt7c.jpg', '../assets/images/dt7d.jpg'],
    },
    {
        id: 8, name: 'The Flash', cost: 560, club: 'Action/Adventure', img: '../assets/images/film8.jpg',
        info: 'Worlds collide when the Flash uses his superpowers to travel back in time to change the events of the past. However, when his attempt to save his family inadvertently alters the future, he becomes trapped in a reality in which General Zod has returned, threatening annihilation.',
        clip: 'https://www.youtube.com/embed/hebWYacbdvc',
        qc: '../assets/images/qc8.jpg',
        dt: ['../assets/images/dt8a.jpg', '../assets/images/dt8b.jpg', '../assets/images/dt8c.jpg', '../assets/images/dt8d.jpg'],
    },
    {
        id: 9, name: 'Medellin', cost: 320, club: 'Action/Adventure', img: '../assets/images/film9.jpg',
        info: 'In order to save his younger brother from the hands of narcos, Reda gathers a team to raid the kidnappers in Medellín, Colombia.',
        clip: 'https://www.youtube.com/embed/sCmCayvkABI',
        qc: '../assets/images/qc9.jpg',
        dt: ['../assets/images/dt9a.jpg', '../assets/images/dt9b.jpg', '../assets/images/dt9c.jpg', '../assets/images/dt9d.jpg'],
    },
    {
        id: 10, name: 'Shazam', cost: 150, club: 'Action/Adventure/Comedy', img: '../assets/images/film10.jpg',
        info: "Two years after Thaddeus Sivana's defeat, Hespera and Kalypso, two of the daughters of the Titan Atlas, break into the Acropolis Museum in Athens, Greece to steal the Wizard's broken staff. The duo then take it to the imprisoned Wizard, forcing him to repair the staff and activate its powers. In Philadelphia, Billy Batson and his 'Shazamily' of foster siblings save people on the collapsing Benjamin Franklin Bridge, but are called out for its destruction. The group is drifting apart at home due to their growing up and having personal interests. Billy is worried about being kicked out of the Vasquez family after he turns 18 and ages out of the foster system. In a dream, as Shazam, Billy is warned by the Wizard about Hespera and Kalypso — he and the Shazamily research the Daughters.",
        clip: 'https://www.youtube.com/embed/4YqsFvQcp0M',
        qc: '../assets/images/qc10.jpg',
        dt: ['../assets/images/dt10a.jpg', '../assets/images/dt10b.jpg', '../assets/images/dt10c.jpg', '../assets/images/dt10d.jpg'],
    },
    {
        id: 11, name: '99 Moons', cost: 400, club: 'Drama/Narrative', img: '../assets/images/film11.jpg',
        info: '99 Moons is about Bigna and Frank as two people with different mindsets. When their different worlds collide, they are drawn into a hauntingly passionate love affair.',
        clip: 'https://www.youtube.com/embed/WeTPSnyhNQI',
        qc: '../assets/images/qc11.jpg',
        dt: ['../assets/images/dt11a.jpg', '../assets/images/dt11b.jpg', '../assets/images/dt11c.jpg', '../assets/images/dt11d.jpg'],
    },
    {
        id: 12, name: 'Newness', cost: 570, club: 'Action/Fiction', img: '../assets/images/film12.jpg',
        info: "Living in Los Angeles, Martin is a divorced pharmacist while Gabriella is a physical therapy assistant from Spain. One night, the two go out with people they met on a dating app. After both dates end badly, they return to the app and match with each other. Meeting at a bar, they spend the rest of the night talking and getting to know each other. In the morning, they return to Martin's apartment and have sex. Soon after, they begin a relationship and Gabriella moves in with Martin.",
        clip: 'https://www.youtube.com/embed/EtBhKTuPjEk',
        qc: '../assets/images/qc12.jpg',
        dt: ['../assets/images/dt12a.jpg', '../assets/images/dt12b.jpg', '../assets/images/dt12c.jpg', '../assets/images/dt12d.jpg'],
    },
    {
        id: 13, name: 'Black Adam', cost: 260, club: 'Action/Fiction', img: '../assets/images/film13.jpg',
        info: "In 2600 BC, the tyrannical king Ahk-Ton of Kahndaq creates the Crown of Sabbac to attain great power. After attempting to stage a revolt, a young slave boy is given the powers of Shazam by the Council of Wizards, transforming him into Kahndaq's heroic champion, who fights Ahk-Ton, killing him and ending his reign. In the present day, Kahndaq is oppressed by the Intergang, a criminal organization, as Adrianna Tomaz, an archaeologist and resistance-fighter, tries to locate the Crown of Sabbac with the help of her brother Karim and their colleagues Samir and Ishmael. As Adrianna obtains the crown, Intergang ambushes them and kills Samir, forcing Adrianna to read an incantation that awakens Teth-Adam, whom she believes to be Kahndaq's champion, from a slumber. As he slaughters most of the Intergang troops, US government official Amanda Waller deems Adam a threat and contacts the Justice Society to apprehend him. Justice Society members Hawkman, Doctor Fate, Cyclone, and Atom Smasher arrive in time to stop Adam's killing spree and explain to Adrianna that Adam was not an entombed savior, but an imprisoned killer.",
        clip: 'https://www.youtube.com/embed/mkomfZHG5q4',
        qc: '../assets/images/qc13.jpg',
        dt: ['../assets/images/dt13a.jpg', '../assets/images/dt13b.jpg', '../assets/images/dt13c.jpg', '../assets/images/dt13d.jpg'],
    },
    {
        id: 14, name: 'Hachiko', cost: 170, club: 'Family', img: '../assets/images/film14.jpg',
        info: "Hachikō, a white Akita, was born on November 10, 1923, at a farm located in Ōdate, Akita Prefecture, Japan. In 1924, Hidesaburō Ueno, a professor in the agriculture department at the Tokyo Imperial University, took Hachikō as a pet and brought him to live in Shibuya, Tokyo. Ueno would commute daily to work, and Hachikō would leave the house to greet him at the end of each day at the nearby Shibuya Station. The pair continued the daily routine until May 21, 1925, when Ueno did not return. The professor had suffered a cerebral hemorrhage while he was giving a lecture to his class, and died without ever returning to the train station at which Hachikō waited.",
        clip: 'https://www.youtube.com/embed/QrPyiBGD9nc',
        qc: '../assets/images/qc14.jpg',
        dt: ['../assets/images/dt14a.jpg', '../assets/images/dt14b.jpg', '../assets/images/dt14c.jpg', '../assets/images/dt14d.jpg'],
    },
    {
        id: 15, name: 'Silo', cost: 320, club: 'Action/Fiction', img: '../assets/images/film15.jpg',
        info: "In a massive underground bunker called the 'Silo', a community thrives without knowing their history, as all records were supposedly destroyed 140 years earlier during a failed rebellion uprising. Sheriff Holston tells Deputy Sam that he wants to 'go out'. Three years earlier, Holston and his wife Allison receive permission to try to become pregnant, but are unsuccessful. During this time Allison learns subversive beliefs about the Silo from Gloria, a fertility expert, and helps a man named George Wilkins explore a forbidden hard drive dating from before the rebellion. Allison tells a skeptical Holston her belief that the people in power have been lying to them and that the view on Silo's screens of a dead outside world are fake. Allison declares that she wants to 'go out', and promises to only clean the Silo's external camera if the outside is beautiful. In accordance with the Silo's Pact, Allison is allowed to leave on a one-way journey. The Silo residents watch as she cleans the camera but collapses shortly after. Two years later, Holston investigates George's death, and meets an engineer named Juliette who claims he was murdered.",
        clip: 'https://www.youtube.com/embed/8ZYhuvIv1pA',
        qc: '../assets/images/qc15.jpg',
        dt: ['../assets/images/dt15a.jpg', '../assets/images/dt15b.jpg', '../assets/images/dt15c.jpg', '../assets/images/dt15d.jpg'],
    },
    {
        id: 16, name: 'XO, Kitty', cost: 410, club: 'Comedy', img: '../assets/images/film16.jpg',
        info: "Kitty Song Covey, who believes she is extremely knowledgeable on love, moves halfway across the world to South Korea, aiming to reconnect with her long-distance boyfriend, Dae. She finds, however, that a relationship is much more complex when it is your own feelings of love at risk.",
        clip: 'https://www.youtube.com/embed/vP9C33H6G3E',
        qc: '../assets/images/qc16.jpg',
        dt: ['../assets/images/dt16a.jpg', '../assets/images/dt16b.jpg', '../assets/images/dt16c.jpg', '../assets/images/dt16d.jpg'],
    },
    {
        id: 17, name: 'Incantation', cost: 523, club: 'Horror', img: '../assets/images/film17.jpg',
        info: "A woman named Li Ronan narrates the film, imploring the viewer to memorize an insignia and chant an incantation to send blessings and lift a curse on her six-year-old daughter, Dodo. The insignia and incantation are interspersed frequently throughout the film to encourage the viewer to pray along. The events of the film are shown as a found footage in a non-linear manner. Six years earlier, Ronan, her boyfriend Dom, and Dom's cousin Yuan, broke a religious taboo while documenting a ritual for their online video channel. They went to a remote clan village inhabited by Dom and Yuan's relatives, who practiced an esoteric Yunnan religion worshipping an ancestral deity called Mother-Buddha. The clan asked the three to submit their names with the incantation to the Mother-Buddha. A clan elder told Ronan that after her daughter was born, she must also submit her daughter's name; Ronan was surprised as she had not realized that she was pregnant.",
        clip: 'https://www.youtube.com/embed/HnyNZdcL_GY',
        qc: '../assets/images/qc17.jpg',
        dt: ['../assets/images/dt17a.jpg', '../assets/images/dt17b.jpg', '../assets/images/dt17c.jpg', '../assets/images/dt17d.jpg'],
    },
    {
        id: 18, name: 'Mr. Zombie', cost: 415, club: 'Action/Fiction', img: '../assets/images/film18.jpg',
        info: "Times of Republican China. Master Ho and his two quick-witted disciples travel the provincial cities. exposing fraudsters who exploit feudal superstition and religious cults.",
        clip: 'https://www.youtube.com/embed/BVDDLWBic1w',
        qc: '../assets/images/qc18.jpg',
        dt: ['../assets/images/dt18a.jpg', '../assets/images/dt18b.jpg', '../assets/images/dt18c.jpg', '../assets/images/dt18d.jpg'],
    },
];